version: '3.8'

services:
  email:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres2018!
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
