

# Config Resend via HTTP
resend.api-key=${RESEND_API_KEY}
resend.from=${RESEND_FROM:Ricardo <ricardo@ricardolm.net>}


spring.datasource.url=${DATA_HOST}
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://127.0.0.1:3000}
app.cors.allow-credentials=${CORS_ALLOW_CREDENTIALS:true}
